///This file is automatically generated. DO NOT EDIT, all your changes would be lost.
class Images {
  Images._();

  static const String assetsImagesMenu = 'assets/images/menu.png';
  static const String audioCollision = 'assets/audio/collision.wav';
  static const String audioFly = 'assets/audio/fly.wav';
  static const String audioPoint = 'assets/audio/point.wav';
  static const String fontsGame = 'assets/fonts/Game.ttf';
  static const String imagesBackground = 'assets/images/background.png';
  static const String imagesBall = 'assets/images/ball.png';
  static const String imagesBirdDownflap = 'assets/images/bird_downflap.png';
  static const String imagesBirdMidflap = 'assets/images/bird_midflap.png';
  static const String imagesBirdUpflap = 'assets/images/bird_upflap.png';
  static const String imagesClouds = 'assets/images/clouds.png';
  static const String imagesGameover = 'assets/images/gameover.png';
  static const String imagesGround = 'assets/images/ground.png';
  static const String imagesMenu = 'assets/images/menu.jpg';
  static const String imagesMessage = 'assets/images/message.png';
  static const String imagesPipe = 'assets/images/pipe.png';
  static const String imagesPipeEnd = 'assets/images/pipe_end.png';
  static const String imagesPipeRode = 'assets/images/pipe_rode.png';
  static const String imagesPipeRotated = 'assets/images/pipe_rotated.png';
}
